### PR TITLE
Fix unicode breakage on truncation

### LINKED ISSUE #7: Probably not unicode safe
This plugin uses String#slice to ensure that messages sizes are accepted by SNS. This check doesn't work for Unicode multibyte chars, and should truncate to the last unicode char < LIMIT.

### PR DESCRIPTION
**Pull request by andrewvc**
Fixes #7 Depends on a logstash snapshot.

### CODE REVIEW

**Comment by suyograo** [comment]
I think this should wait until the 1.5.3 GA release. it seems awkward releasing this plugin which has a dependency on a snapshot version. It should be ok for testing, though. When 1.5.3 logstash-core gem is released we can make the min version: `s.add_runtime_dependency "logstash-core", '>= 1.5.3'` and publish it @andrewvc thoughts?

**Comment by andrewvc** [comment]
Yup! I just pushed this up for review

**Comment by suyograo** [comment]
The snapshot gem has been published

**Comment by jordansissel** [comment]
LGTM; didn't test, but I remember testing the library that this calls and all was cool. :)

**Pull request closed without merging**
